name = "rad"
version = "1.2.1-dev"
description = "A task runner for Gleam projects"
licences = ["Apache-2.0"]
target = "javascript"
gleam = ">= 0.34.0"

[repository]
repo = "rad"
user = "tynanbe"
type = "github"

[[links]]
href = "https://gleam.run/"
title = "Website"

[dependencies]
gleam_http = "~> 3.5"
gleam_httpc = "~> 2.1"
gleam_json = "~> 0.7 or ~> 1.0"
gleam_stdlib = "~> 0.34 or ~> 1.0"
glint = "~> 0.16"
shellout = "~> 1.6"
snag = "~> 0.3 or ~> 1.0"
thoas = "~> 0.4 or ~> 1.0"
tomerl = "~> 0.5 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"

[javascript.deno]
allow_all = true

[rad]
workbook = "rad/workbook/standard"
targets = ["erlang", "javascript"]
with = "javascript"

[[rad.formatters]]
name = "erlang"
check = ["erlfmt", "--check"]
run = ["erlfmt", "--write", "src/rad_ffi.erl", "src/file_ffi.erl"]

[[rad.formatters]]
name = "javascript"
check = ["deno", "fmt", "--check"]
run = ["deno", "fmt"]

[[rad.tasks]]
path = ["purple", "heart"]
run = ["echo", "💜 The dream you'll have here is a dream within a dream."]
shortdoc = "💜 The dream you'll have here is a dream within a dream."

[[rad.tasks]]
path = ["sparkles"]
run = ["echo", "✨ It's been a long road getting here..."]

[[rad.tasks]]
path = ["sparkling", "heart"]
run = ["sh", "-euc", """
  echo \
    💖 I was staring out the window and there it was, just fluttering there... \
    $(rad version)!
"""]
